version: "3.6"

services:
  profile:
    build: "."
    command: "profile-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: "profile"
      POSTGRES_USER: "profile"
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: "nats:4222"
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "profile"
      POSTGRES_USER: "profile"
      POSTGRES_PASSWORD: "123456"
  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"
